### ISSUE TITLE
Docker failed to run

### ISSUE THREAD

**Issue by zerjioang** [nveloso/conkas#10] opened 2022-04-28 14:09 UTC
Docker fails with error:  **Exception: Could not deserialize ATN with version  (expected 4).**

```bash
docker build -t conkas:6aee098 .
```
```bash
Sending build context to Docker daemon  11.77MB
Step 1/14 : FROM ubuntu:20.04
 ---> 2b4cba85892a
Step 2/14 : RUN apt-get update && apt-get install -y python3-pip
 ---> Using cache
 ---> 9af4ed5228bf
Step 3/14 : RUN apt-get autoremove -y
 ---> Using cache
 ---> c8e917b7a911
Step 4/14 : RUN apt-get clean
 ---> Using cache
 ---> 4e282c0baae4
Step 5/14 : ENV LC_ALL C.UTF-8
 ---> Using cache
 ---> bbc0c0223171
Step 6/14 : RUN pip3 --no-cache-dir install --upgrade setuptools pip
 ---> Using cache
 ---> ac3ff96a720d
Step 7/14 : COPY . /conkas/
 ---> 4d02377b7211
Step 8/14 : WORKDIR /conkas
 ---> Running in a2572033033e
Removing intermediate container a2572033033e
 ---> f234c9ead0b2
Step 9/14 : RUN pip3 install -r requirements.txt
 ---> Running in 86cf4643d8a0
Collecting pyevmasm==0.2.3
  Downloading pyevmasm-0.2.3-py3-none-any.whl (15 kB)
Collecting cbor2==5.1.2
  Downloading cbor2-5.1.2.tar.gz (73 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.2/73.2 KB 1.5 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting z3-solver==4.8.8.0
  Downloading z3_solver-4.8.8.0-py2.py3-none-manylinux1_x86_64.whl (29.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 29.6/29.6 MB 9.3 MB/s eta 0:00:00
Collecting pycryptodome==3.9.8
  Downloading pycryptodome-3.9.8-cp38-cp38-manylinux1_x86_64.whl (13.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.7/13.7 MB 10.1 MB/s eta 0:00:00
Collecting py-solc-x==0.10.1
  Downloading py_solc_x-0.10.1-py3-none-any.whl (15 kB)
Collecting solidity_parser==0.0.7
  Downloading solidity-parser-0.0.7.tar.gz (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.4/58.4 KB 4.3 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting future
  Downloading future-0.18.2.tar.gz (829 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 829.2/829.2 KB 9.1 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting requests<3,>=2.19.0
  Downloading requests-2.27.1-py2.py3-none-any.whl (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.1/63.1 KB 5.4 MB/s eta 0:00:00
Collecting semantic-version<3,>=2.8.1
  Downloading semantic_version-2.9.0-py2.py3-none-any.whl (15 kB)
Collecting antlr4-python3-runtime
  Downloading antlr4-python3-runtime-4.10.tar.gz (116 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.6/116.6 KB 8.0 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting idna<4,>=2.5
  Downloading idna-3.3-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 KB 5.8 MB/s eta 0:00:00
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.9-py2.py3-none-any.whl (138 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.0/139.0 KB 7.6 MB/s eta 0:00:00
Collecting certifi>=2017.4.17
  Downloading certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 149.2/149.2 KB 7.6 MB/s eta 0:00:00
Collecting charset-normalizer~=2.0.0
  Downloading charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Building wheels for collected packages: cbor2, solidity_parser, antlr4-python3-runtime, future
  Building wheel for cbor2 (setup.py): started
  Building wheel for cbor2 (setup.py): finished with status 'done'
  Created wheel for cbor2: filename=cbor2-5.1.2-cp38-cp38-linux_x86_64.whl size=172592 sha256=f99f7795c9499faffea9662a0f039c84523d75cc771ebbdfd7ba3fa9d1297256
  Stored in directory: /root/.cache/pip/wheels/ee/62/04/40cf369149e4f154952feb7c9a64f00ffa35b64cd2bfa5c3dd
  Building wheel for solidity_parser (setup.py): started
  Building wheel for solidity_parser (setup.py): finished with status 'done'
  Created wheel for solidity_parser: filename=solidity_parser-0.0.7-py3-none-any.whl size=59431 sha256=5b2ccbbd74fe29b2e2607fb1073962f59d624ce168d7251e24b11575c30b6e31
  Stored in directory: /root/.cache/pip/wheels/66/c8/8e/950d868762471f076ae5eff4c337a78ccacfe655d64a8b9021
  Building wheel for antlr4-python3-runtime (setup.py): started
  Building wheel for antlr4-python3-runtime (setup.py): finished with status 'done'
  Created wheel for antlr4-python3-runtime: filename=antlr4_python3_runtime-4.10-py3-none-any.whl size=144169 sha256=79556d4e4e9869397a3be6153f7054a118f138cd437bb707b514e574e36d5de9
  Stored in directory: /root/.cache/pip/wheels/b6/ad/fa/3b3f55bd8f984116397a4da5b33a4f9be7df18c2be0ba972e4
  Building wheel for future (setup.py): started
  Building wheel for future (setup.py): finished with status 'done'
  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491070 sha256=58c5a580b8e9e77f40dd7bb9c413143dca73a910bb4ce4dc79372d26b34b1b2d
  Stored in directory: /root/.cache/pip/wheels/8e/70/28/3d6ccd6e315f65f245da085482a2e1c7d14b90b30f239e2cf4
Successfully built cbor2 solidity_parser antlr4-python3-runtime future
Installing collected packages: z3-solver, certifi, cbor2, antlr4-python3-runtime, urllib3, solidity_parser, semantic-version, pycryptodome, idna, future, charset-normalizer, requests, pyevmasm, py-solc-x
Successfully installed antlr4-python3-runtime-4.10 cbor2-5.1.2 certifi-2021.10.8 charset-normalizer-2.0.12 future-0.18.2 idna-3.3 py-solc-x-0.10.1 pycryptodome-3.9.8 pyevmasm-0.2.3 requests-2.27.1 semantic-version-2.9.0 solidity_parser-0.0.7 urllib3-1.26.9 z3-solver-4.8.8.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Removing intermediate container 86cf4643d8a0
 ---> efa2d93b2c35
Step 10/14 : RUN python3 -m solcx.install v0.4.25
 ---> Running in 40bce25bb3c5
solc, the solidity compiler commandline interface
Version: 0.4.25+commit.59dbf8f1.Linux.g++
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'solcx.install' found in sys.modules after import of package 'solcx', but prior to execution of 'solcx.install'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Removing intermediate container 40bce25bb3c5
 ---> 2ccb7af636cb
Step 11/14 : RUN python3 -m solcx.install v0.4.26
 ---> Running in cd6fc37d4aff
solc, the solidity compiler commandline interface
Version: 0.4.26+commit.4563c3fc.Linux.g++
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'solcx.install' found in sys.modules after import of package 'solcx', but prior to execution of 'solcx.install'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Removing intermediate container cd6fc37d4aff
 ---> 0036db74c61e
Step 12/14 : RUN python3 -m solcx.install v0.5.17
 ---> Running in f52f6fda5c71
solc, the solidity compiler commandline interface
Version: 0.5.17+commit.d19bba13.Linux.g++
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'solcx.install' found in sys.modules after import of package 'solcx', but prior to execution of 'solcx.install'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Removing intermediate container f52f6fda5c71
 ---> 79b7713a74c7
Step 13/14 : RUN python3 -m solcx.install v0.6.11
 ---> Running in f9b298c0954b
solc, the solidity compiler commandline interface
Version: 0.6.11+commit.5ef660b1.Linux.g++
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'solcx.install' found in sys.modules after import of package 'solcx', but prior to execution of 'solcx.install'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Removing intermediate container f9b298c0954b
 ---> a91014faf059
Step 14/14 : ENTRYPOINT ["python3", "conkas.py"]
 ---> Running in 9239a1c9a329
Removing intermediate container 9239a1c9a329
 ---> 33f74e98a7bc
Successfully built 33f74e98a7bc
Successfully tagged conkas:6aee098
```

```bash
➜  conkas git:(master) docker run -it conkas:6aee098 -vt reentrancy example.sol
Traceback (most recent call last):
  File "conkas.py", line 7, in <module>
    from solidity_parser.parser import parse
  File "/usr/local/lib/python3.8/dist-packages/solidity_parser/__init__.py", line 1, in <module>
    from .parser import parse_file, parse, objectify, visit
  File "/usr/local/lib/python3.8/dist-packages/solidity_parser/parser.py", line 10, in <module>
    from solidity_parser.solidity_antlr4.SolidityLexer import SolidityLexer
  File "/usr/local/lib/python3.8/dist-packages/solidity_parser/solidity_antlr4/SolidityLexer.py", line 783, in <module>
    class SolidityLexer(Lexer):
  File "/usr/local/lib/python3.8/dist-packages/solidity_parser/solidity_antlr4/SolidityLexer.py", line 785, in SolidityLexer
    atn = ATNDeserializer().deserialize(serializedATN())
  File "/usr/local/lib/python3.8/dist-packages/antlr4/atn/ATNDeserializer.py", line 28, in deserialize
    self.checkVersion()
  File "/usr/local/lib/python3.8/dist-packages/antlr4/atn/ATNDeserializer.py", line 50, in checkVersion
    raise Exception("Could not deserialize ATN with version " + str(version) + " (expected " + str(SERIALIZED_VERSION) + ").")
Exception: Could not deserialize ATN with version  (expected 4).
```

**Comment by nveloso** [comment] 2022-05-01 18:16
The problem seems related to `antlr4-python3-runtime` dependency. I think they updated the library and the new version is not back compatible... The root problem is because the `solidity_parser` library in the version that I pinned they did not pin the `antlr4-python3-runtime` dependency.

The easiest way to fix the problem is to pin `antlr4-python3-runtime` to some version. I have to test which version will work.

**Comment by zerjioang** [comment] 2022-05-02 11:22
@nveloso I see. So, pinning the version should fix the issue, right?

**Comment by htkcodes** [comment] 2022-05-27 14:15
How do you pin?

**Comment by nveloso** [comment] 2022-05-31 22:24
I updated the `requirements.txt` file to pin a specific version of `antlr4-python3-runtime` dependency.
I will close this issue since my PR fixes the problem. You can open this again if you have the same problem.

**Closed as completed by nveloso** 2022-05-31 22:24 UTC
